//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankOfIsraelInterestType
    {
        public BankOfIsraelInterestType()
        {
            this.BankOfIsraelInterestRates = new HashSet<BankOfIsraelInterestRate>();
        }
    
        public int ID { get; set; }
        public string BOIIndexType { get; set; }
    
        public virtual ICollection<BankOfIsraelInterestRate> BankOfIsraelInterestRates { get; set; }
    }
}
