//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPITable
    {
        public int Year { get; set; }
        public int BaseYear { get; set; }
        public decimal Multiplier { get; set; }
        public int Month { get; set; }
        public decimal Value { get; set; }
        public int IndexType { get; set; }
    
        public virtual IndexType IndexType1 { get; set; }
    }
}
