//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealType
    {
        public DealType()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string DealType1 { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
