//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionStatu
    {
        public ExecutionStatu()
        {
            this.Executions = new HashSet<Execution>();
        }
    
        public int ID { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Execution> Executions { get; set; }
    }
}
