//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Execution
    {
        public Execution()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int ID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool InNewInstance { get; set; }
        public System.DateTime InstanceCreatedOn { get; set; }
        public string InstanceType { get; set; }
        public string InstanceID { get; set; }
        public int ExecutionStatus { get; set; }
        public System.DateTime DateSoftwareLaunch { get; set; }
        public System.DateTime CalculationStartedOn { get; set; }
        public Nullable<System.DateTime> CalculationEndedOn { get; set; }
        public Nullable<System.DateTime> DateSoftwareClosed { get; set; }
        public Nullable<System.DateTime> DateInstanceClosed { get; set; }
        public int SoftwareRunNumber { get; set; }
        public decimal VMCostPerHour { get; set; }
    
        public virtual ExecutionStatu ExecutionStatu { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual Order Order { get; set; }
    }
}
