//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexType
    {
        public IndexType()
        {
            this.CPITables = new HashSet<CPITable>();
        }
    
        public int ID { get; set; }
        public string IndexType1 { get; set; }
    
        public virtual ICollection<CPITable> CPITables { get; set; }
    }
}
