//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public bool IsBilling { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int NumberOfPayments { get; set; }
        public int CurrencyID { get; set; }
        public string Link { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Order Order { get; set; }
    }
}
