//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListBank
    {
        public ListBank()
        {
            this.TrackInterestRates = new HashSet<TrackInterestRate>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Orders2 = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int BankNumber { get; set; }
        public string Name { get; set; }
        public bool PrimaryOption { get; set; }
        public bool Available { get; set; }
    
        public virtual ICollection<TrackInterestRate> TrackInterestRates { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<Order> Orders2 { get; set; }
    }
}
