//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListedTrack
    {
        public ListedTrack()
        {
            this.TrackInterestRates = new HashSet<TrackInterestRate>();
            this.Tracks = new HashSet<Track>();
            this.ResultTracks = new HashSet<ResultTrack>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Inflated { get; set; }
        public int MinTimeMonths { get; set; }
        public int MaxTimeMonth { get; set; }
        public int JumpsInMonths { get; set; }
    
        public virtual ICollection<TrackInterestRate> TrackInterestRates { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
        public virtual ICollection<ResultTrack> ResultTracks { get; set; }
    }
}
