//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObligationOrFuture
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int Type { get; set; }
        public int Amount { get; set; }
        public int EndYear { get; set; }
        public int EndMonth { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
