//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersOrCheck
    {
        public OffersOrCheck()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public int ID { get; set; }
        public int Type { get; set; }
        public Nullable<int> ApprovingBank { get; set; }
        public int OrderID { get; set; }
    
        public virtual ICollection<Track> Tracks { get; set; }
        public virtual Order Order { get; set; }
    }
}
