//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ChangePreferences = new HashSet<ChangePreference>();
            this.Executions = new HashSet<Execution>();
            this.Invoices = new HashSet<Invoice>();
            this.ObligationOrFutures = new HashSet<ObligationOrFuture>();
            this.OffersOrChecks = new HashSet<OffersOrCheck>();
            this.Savings1 = new HashSet<Saving>();
            this.ListBanks = new HashSet<ListBank>();
            this.ResultEntries = new HashSet<ResultEntry>();
        }
    
        public int ID { get; set; }
        public string Label { get; set; }
        public int UserID { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int DealType { get; set; }
        public int NumberOfLoaners { get; set; }
        public int YoungestLoanerAge { get; set; }
        public int TotalNetIncome { get; set; }
        public bool Obligations { get; set; }
        public bool FutureMoney { get; set; }
        public int PropertyValue { get; set; }
        public int DesiredLoanAmount { get; set; }
        public int DesiredMonthlyPayment { get; set; }
        public bool RefinanceCheck { get; set; }
        public bool BankOffers { get; set; }
        public int PlanningPreference { get; set; }
        public int StabilityPreference { get; set; }
        public bool ChangesPreference { get; set; }
        public int Relations { get; set; }
        public bool Savings { get; set; }
        public Nullable<int> MainAccount { get; set; }
        public Nullable<int> SecondaryAccount { get; set; }
        public Nullable<int> EntranceMonth { get; set; }
        public Nullable<int> EntranceYear { get; set; }
        public Nullable<int> CurrentRent { get; set; }
        public Nullable<decimal> InitialCalculatedTotal { get; set; }
        public string PlanningValue { get; set; }
        public string StabilityValue { get; set; }
    
        public virtual ICollection<ChangePreference> ChangePreferences { get; set; }
        public virtual DealType DealType1 { get; set; }
        public virtual ICollection<Execution> Executions { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ListBank ListBank { get; set; }
        public virtual ListBank ListBank1 { get; set; }
        public virtual ICollection<ObligationOrFuture> ObligationOrFutures { get; set; }
        public virtual ICollection<OffersOrCheck> OffersOrChecks { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Saving> Savings1 { get; set; }
        public virtual ICollection<ListBank> ListBanks { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual ICollection<ResultEntry> ResultEntries { get; set; }
    }
}
