//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultEntry
    {
        public ResultEntry()
        {
            this.ResultTracks = new HashSet<ResultTrack>();
        }
    
        public int ID { get; set; }
        public int ExecutionID { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<ResultTrack> ResultTracks { get; set; }
    }
}
