//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultTrack
    {
        public int ID { get; set; }
        public int ResultEntryID { get; set; }
        public int Amount { get; set; }
        public int TrackType { get; set; }
        public int Time { get; set; }
        public bool Inflation { get; set; }
        public decimal Rate { get; set; }
        public int PMT { get; set; }
        public int TotalPay { get; set; }
    
        public virtual ResultEntry ResultEntry { get; set; }
        public virtual ListedTrack ListedTrack { get; set; }
    }
}
