//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsType
    {
        public SavingsType()
        {
            this.Savings = new HashSet<Saving>();
        }
    
        public int ID { get; set; }
        public string SavingTypeName { get; set; }
    
        public virtual ICollection<Saving> Savings { get; set; }
    }
}
