//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int ID { get; set; }
        public int OfferOrCheckID { get; set; }
        public Nullable<int> YearTaken { get; set; }
        public Nullable<int> MonthTaken { get; set; }
        public int Amount { get; set; }
        public int TrackType { get; set; }
        public int Time { get; set; }
        public bool Inflation { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> PMT { get; set; }
    
        public virtual ListedTrack ListedTrack { get; set; }
        public virtual OffersOrCheck OffersOrCheck { get; set; }
    }
}
