//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shrink2FitDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackInterestRate
    {
        public int BankID { get; set; }
        public int TrackID { get; set; }
        public int Period { get; set; }
        public decimal Rate { get; set; }
    
        public virtual ListBank ListBank { get; set; }
        public virtual ListedTrack ListedTrack { get; set; }
    }
}
